### ISSUE TITLE
How to use vault secrets?

### ISSUE THREAD

**Issue by amedee** [roles-ansible/check-ansible-ubuntu-latest-action#1]
In my playbook I have
```
  vars_files:
    - secret
```
I got this error:
> ERROR! Attempting to decrypt but no vault secrets found

When running `check-ansible-ubuntu-latest-action`, how do I tell it what the secret password is, without actually adding that to my repository or making it otherwise visible to the public?

I am using it as a GitHub action: https://github.com/marketplace/actions/check-ansible-ubuntu-latest

**Comment by amedee** [comment]
Never mind, I just discovered Encrypted secrets in the GitHub Actions Reference: https://docs.github.com/en/actions/reference/encrypted-secrets

Sharing the link for everyone else who may have the sane question.

Closing issue.

**Comment by DO1JLR** [comment]
:heart:
